version: '3.8'

services:
  web:
    image: python:3.11
    container_name: app-gestion
    ports:
      - "8083:5000"
    volumes:
      - ./:/app
    working_dir: /app
    command: |
      bash -c "
        apt-get update && apt-get install -y iputils-ping && 
        pip install -r requirements.txt && 
        python3 app.py
      "
    environment:
      - PHP_ENV=development
    restart: always